import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/Components/NavBar/NavBar";
import Sliders from "@/Components/Sliders/Sliders";
import Experience from "@/Components/Experience/Experience";
import MiniCards from "@/Components/MiniCards/MiniCards";
import { Col, Container, Row } from "react-bootstrap";
import Footer from "@/Components/Footer/Footer";
import { useSelector, useDispatch } from "react-redux";
import { setLogin, setLogout } from "../Store/UserSlice";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-dark">
        <NavBar login="SignIn" SignUp="SignUp" />
        <hr className="line" />
        <Experience />
        <hr className="line" />
        <br />
        <br />
        <Container className="ContainerSet Container">
          <Container className="ContainerSet Container">
            <br />
            <br />
            <Row>
              <Col md={6}>
                <MiniCards
                  title="Creating Events"
                  src={"/minicard.svg"}
                  detail="Create Your Own Event in Our Website"
                  buttoninfo="Create Event"
                  hlink={"/SignIn"}
                />
              </Col>
              <Col md={6}>
                <MiniCards
                  title="Tracking RSVPs"
                  src={"/card2.png"}
                  detail="Manage Someone Event in Our Website"
                  buttoninfo="Manage Event"
                  hlink={"/"}
                />
              </Col>
            </Row>
          </Container>
          <hr className="line" />
          <Container className="ContainerSet Container bg-dark">
            <br />
            <br />
            <Row>
              <Col md={6}>
                <MiniCards
                  title="Inviting Attendees"
                  src={"/card3.png"}
                  detail="Invite Different attendies in your event by posting your event"
                  buttoninfo="Invite Attendies"
                  hlink={"/"}
                />
              </Col>
              <Col md={6}>
                <MiniCards
                  title="Manage Events"
                  src={"/card4.jpg"}
                  detail="Manage Someone Event in Our Website"
                  buttoninfo="Manage Event"
                  hlink={"/"}
                />
              </Col>
            </Row>
          </Container>
        </Container>
        <hr className="line" />
        <Footer />
        {/* <Sliders /> */}
      </main>
    </>
  );
}
